/* Generated by gbrecomp from Pokemon Pinball (U)  */
#include "Pokemon_Pinball__U___internal.h"
#include "gbrt.h"
#include <stdio.h>
#include <stdlib.h>

/* Bank dispatch - routes calls to the correct bank function */
void Pokemon_Pinball__U___dispatch_00(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_01(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_02(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_03(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_04(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_05(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_06(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_07(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_08(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_09(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_0a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_0b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_0c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_0d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_0e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_0f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_10(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_11(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_12(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_13(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_14(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_15(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_16(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_17(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_18(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_19(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_1a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_1b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_1c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_1d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_1e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_1f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_20(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_21(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_22(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_23(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_24(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_25(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_26(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_27(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_28(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_29(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_2a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_2b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_2c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_2d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_2e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_2f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_30(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_31(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_32(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_33(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_34(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_35(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_36(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_37(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_38(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_39(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_3a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_3b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_3c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_3d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_3e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_3f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_40(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_41(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_42(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_43(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_44(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_45(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_46(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_47(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_48(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_49(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_4a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_4b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_4c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_4d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_4e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_4f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_50(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_51(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_52(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_53(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_54(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_55(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_56(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_57(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_58(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_59(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_5a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_5b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_5c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_5d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_5e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_5f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_60(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_61(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_62(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_63(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_64(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_65(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_66(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_67(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_68(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_69(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_6a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_6b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_6c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_6d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_6e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_6f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_70(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_71(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_72(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_73(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_74(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_75(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_76(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_77(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_78(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_79(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_7a(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_7b(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_7c(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_7d(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_7e(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_7f(GBContext* ctx, uint16_t addr, uint16_t bank);
void Pokemon_Pinball__U___dispatch_ff(GBContext* ctx, uint16_t addr, uint16_t bank);

static uint8_t ram_overlay_0_matches(GBContext* ctx) {
    if (gb_read8(ctx, 0xff80) != 0x3e) return 0;
    if (gb_read8(ctx, 0xff81) != 0xd0) return 0;
    if (gb_read8(ctx, 0xff82) != 0xe0) return 0;
    if (gb_read8(ctx, 0xff83) != 0x46) return 0;
    if (gb_read8(ctx, 0xff84) != 0x3e) return 0;
    if (gb_read8(ctx, 0xff85) != 0x28) return 0;
    if (gb_read8(ctx, 0xff86) != 0x3d) return 0;
    if (gb_read8(ctx, 0xff87) != 0x20) return 0;
    if (gb_read8(ctx, 0xff88) != 0xfd) return 0;
    if (gb_read8(ctx, 0xff89) != 0xc9) return 0;
    return 1;
}

static uint8_t try_dispatch_compiled_ram_overlay(GBContext* ctx, uint16_t addr, uint16_t bank) {
    if (addr >= 0xff80 && addr < 0xff8a) {
        if (!ram_overlay_0_matches(ctx)) {
            return 0;
        }
        switch (addr) {
            case 0xff80:
                Pokemon_Pinball__U___dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff81:
                Pokemon_Pinball__U___dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff82:
                Pokemon_Pinball__U___dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff84:
                Pokemon_Pinball__U___dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff86:
                Pokemon_Pinball__U___dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff87:
                Pokemon_Pinball__U___dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff88:
                Pokemon_Pinball__U___dispatch_ff(ctx, addr, bank);
                return 1;
            case 0xff89:
                Pokemon_Pinball__U___dispatch_ff(ctx, addr, bank);
                return 1;
            default:
                return 0;
        }
    }
    return 0;
}

void gb_dispatch(GBContext* ctx, uint16_t addr) {
    ctx->pc = addr;
    while (!ctx->stopped && !ctx->halted) {
        gbrt_note_generated_indirect_dispatch(ctx);
        addr = ctx->pc;
        uint16_t bank = gb_resolve_rom_bank(ctx, addr);
        if (gbrt_instruction_limit > 0) {
            if (gbrt_instruction_count >= gbrt_instruction_limit) {
                fprintf(stderr, "[LIMIT] Reached instruction limit %llu\n", (unsigned long long)gbrt_instruction_limit);
                exit(0);
            }
            gbrt_instruction_count++;
        }
        if (ctx->trace_entries_enabled) gbrt_log_trace(ctx, bank, addr);
        if (gbrt_trace_enabled) {
            fprintf(stderr, "[TRACE] Dispatch 0x%04X (Bank %d)\n", addr, bank);
        }
        if (gbrt_try_execute_hram_stub(ctx, addr)) {
            if (ctx->single_step_mode) break;
            continue;
        }
        if (gbrt_try_execute_highmem_stub(ctx, addr)) {
            if (ctx->single_step_mode || gbrt_generated_safepoint(ctx)) break;
            continue;
        }
        if (gbrt_try_execute_ram_stub(ctx, addr)) {
            if (ctx->single_step_mode || gbrt_generated_safepoint(ctx)) break;
            continue;
        }
        if (try_dispatch_compiled_ram_overlay(ctx, addr, bank)) {
            if (ctx->single_step_mode || gbrt_generated_safepoint(ctx)) break;
            continue;
        }
        if (addr >= 0xFF80 && addr <= 0xFFFE) {
            gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_WRITABLE_HRAM, 0);
            if (ctx->single_step_mode || gbrt_generated_safepoint(ctx)) break;
            continue;
        }
        switch (addr >> 8) {
            case 0x00: Pokemon_Pinball__U___dispatch_00(ctx, addr, bank); break;
            case 0x01: Pokemon_Pinball__U___dispatch_01(ctx, addr, bank); break;
            case 0x02: Pokemon_Pinball__U___dispatch_02(ctx, addr, bank); break;
            case 0x03: Pokemon_Pinball__U___dispatch_03(ctx, addr, bank); break;
            case 0x04: Pokemon_Pinball__U___dispatch_04(ctx, addr, bank); break;
            case 0x05: Pokemon_Pinball__U___dispatch_05(ctx, addr, bank); break;
            case 0x06: Pokemon_Pinball__U___dispatch_06(ctx, addr, bank); break;
            case 0x07: Pokemon_Pinball__U___dispatch_07(ctx, addr, bank); break;
            case 0x08: Pokemon_Pinball__U___dispatch_08(ctx, addr, bank); break;
            case 0x09: Pokemon_Pinball__U___dispatch_09(ctx, addr, bank); break;
            case 0x0a: Pokemon_Pinball__U___dispatch_0a(ctx, addr, bank); break;
            case 0x0b: Pokemon_Pinball__U___dispatch_0b(ctx, addr, bank); break;
            case 0x0c: Pokemon_Pinball__U___dispatch_0c(ctx, addr, bank); break;
            case 0x0d: Pokemon_Pinball__U___dispatch_0d(ctx, addr, bank); break;
            case 0x0e: Pokemon_Pinball__U___dispatch_0e(ctx, addr, bank); break;
            case 0x0f: Pokemon_Pinball__U___dispatch_0f(ctx, addr, bank); break;
            case 0x10: Pokemon_Pinball__U___dispatch_10(ctx, addr, bank); break;
            case 0x11: Pokemon_Pinball__U___dispatch_11(ctx, addr, bank); break;
            case 0x12: Pokemon_Pinball__U___dispatch_12(ctx, addr, bank); break;
            case 0x13: Pokemon_Pinball__U___dispatch_13(ctx, addr, bank); break;
            case 0x14: Pokemon_Pinball__U___dispatch_14(ctx, addr, bank); break;
            case 0x15: Pokemon_Pinball__U___dispatch_15(ctx, addr, bank); break;
            case 0x16: Pokemon_Pinball__U___dispatch_16(ctx, addr, bank); break;
            case 0x17: Pokemon_Pinball__U___dispatch_17(ctx, addr, bank); break;
            case 0x18: Pokemon_Pinball__U___dispatch_18(ctx, addr, bank); break;
            case 0x19: Pokemon_Pinball__U___dispatch_19(ctx, addr, bank); break;
            case 0x1a: Pokemon_Pinball__U___dispatch_1a(ctx, addr, bank); break;
            case 0x1b: Pokemon_Pinball__U___dispatch_1b(ctx, addr, bank); break;
            case 0x1c: Pokemon_Pinball__U___dispatch_1c(ctx, addr, bank); break;
            case 0x1d: Pokemon_Pinball__U___dispatch_1d(ctx, addr, bank); break;
            case 0x1e: Pokemon_Pinball__U___dispatch_1e(ctx, addr, bank); break;
            case 0x1f: Pokemon_Pinball__U___dispatch_1f(ctx, addr, bank); break;
            case 0x20: Pokemon_Pinball__U___dispatch_20(ctx, addr, bank); break;
            case 0x21: Pokemon_Pinball__U___dispatch_21(ctx, addr, bank); break;
            case 0x22: Pokemon_Pinball__U___dispatch_22(ctx, addr, bank); break;
            case 0x23: Pokemon_Pinball__U___dispatch_23(ctx, addr, bank); break;
            case 0x24: Pokemon_Pinball__U___dispatch_24(ctx, addr, bank); break;
            case 0x25: Pokemon_Pinball__U___dispatch_25(ctx, addr, bank); break;
            case 0x26: Pokemon_Pinball__U___dispatch_26(ctx, addr, bank); break;
            case 0x27: Pokemon_Pinball__U___dispatch_27(ctx, addr, bank); break;
            case 0x28: Pokemon_Pinball__U___dispatch_28(ctx, addr, bank); break;
            case 0x29: Pokemon_Pinball__U___dispatch_29(ctx, addr, bank); break;
            case 0x2a: Pokemon_Pinball__U___dispatch_2a(ctx, addr, bank); break;
            case 0x2b: Pokemon_Pinball__U___dispatch_2b(ctx, addr, bank); break;
            case 0x2c: Pokemon_Pinball__U___dispatch_2c(ctx, addr, bank); break;
            case 0x2d: Pokemon_Pinball__U___dispatch_2d(ctx, addr, bank); break;
            case 0x2e: Pokemon_Pinball__U___dispatch_2e(ctx, addr, bank); break;
            case 0x2f: Pokemon_Pinball__U___dispatch_2f(ctx, addr, bank); break;
            case 0x30: Pokemon_Pinball__U___dispatch_30(ctx, addr, bank); break;
            case 0x31: Pokemon_Pinball__U___dispatch_31(ctx, addr, bank); break;
            case 0x32: Pokemon_Pinball__U___dispatch_32(ctx, addr, bank); break;
            case 0x33: Pokemon_Pinball__U___dispatch_33(ctx, addr, bank); break;
            case 0x34: Pokemon_Pinball__U___dispatch_34(ctx, addr, bank); break;
            case 0x35: Pokemon_Pinball__U___dispatch_35(ctx, addr, bank); break;
            case 0x36: Pokemon_Pinball__U___dispatch_36(ctx, addr, bank); break;
            case 0x37: Pokemon_Pinball__U___dispatch_37(ctx, addr, bank); break;
            case 0x38: Pokemon_Pinball__U___dispatch_38(ctx, addr, bank); break;
            case 0x39: Pokemon_Pinball__U___dispatch_39(ctx, addr, bank); break;
            case 0x3a: Pokemon_Pinball__U___dispatch_3a(ctx, addr, bank); break;
            case 0x3b: Pokemon_Pinball__U___dispatch_3b(ctx, addr, bank); break;
            case 0x3c: Pokemon_Pinball__U___dispatch_3c(ctx, addr, bank); break;
            case 0x3d: Pokemon_Pinball__U___dispatch_3d(ctx, addr, bank); break;
            case 0x3e: Pokemon_Pinball__U___dispatch_3e(ctx, addr, bank); break;
            case 0x3f: Pokemon_Pinball__U___dispatch_3f(ctx, addr, bank); break;
            case 0x40: Pokemon_Pinball__U___dispatch_40(ctx, addr, bank); break;
            case 0x41: Pokemon_Pinball__U___dispatch_41(ctx, addr, bank); break;
            case 0x42: Pokemon_Pinball__U___dispatch_42(ctx, addr, bank); break;
            case 0x43: Pokemon_Pinball__U___dispatch_43(ctx, addr, bank); break;
            case 0x44: Pokemon_Pinball__U___dispatch_44(ctx, addr, bank); break;
            case 0x45: Pokemon_Pinball__U___dispatch_45(ctx, addr, bank); break;
            case 0x46: Pokemon_Pinball__U___dispatch_46(ctx, addr, bank); break;
            case 0x47: Pokemon_Pinball__U___dispatch_47(ctx, addr, bank); break;
            case 0x48: Pokemon_Pinball__U___dispatch_48(ctx, addr, bank); break;
            case 0x49: Pokemon_Pinball__U___dispatch_49(ctx, addr, bank); break;
            case 0x4a: Pokemon_Pinball__U___dispatch_4a(ctx, addr, bank); break;
            case 0x4b: Pokemon_Pinball__U___dispatch_4b(ctx, addr, bank); break;
            case 0x4c: Pokemon_Pinball__U___dispatch_4c(ctx, addr, bank); break;
            case 0x4d: Pokemon_Pinball__U___dispatch_4d(ctx, addr, bank); break;
            case 0x4e: Pokemon_Pinball__U___dispatch_4e(ctx, addr, bank); break;
            case 0x4f: Pokemon_Pinball__U___dispatch_4f(ctx, addr, bank); break;
            case 0x50: Pokemon_Pinball__U___dispatch_50(ctx, addr, bank); break;
            case 0x51: Pokemon_Pinball__U___dispatch_51(ctx, addr, bank); break;
            case 0x52: Pokemon_Pinball__U___dispatch_52(ctx, addr, bank); break;
            case 0x53: Pokemon_Pinball__U___dispatch_53(ctx, addr, bank); break;
            case 0x54: Pokemon_Pinball__U___dispatch_54(ctx, addr, bank); break;
            case 0x55: Pokemon_Pinball__U___dispatch_55(ctx, addr, bank); break;
            case 0x56: Pokemon_Pinball__U___dispatch_56(ctx, addr, bank); break;
            case 0x57: Pokemon_Pinball__U___dispatch_57(ctx, addr, bank); break;
            case 0x58: Pokemon_Pinball__U___dispatch_58(ctx, addr, bank); break;
            case 0x59: Pokemon_Pinball__U___dispatch_59(ctx, addr, bank); break;
            case 0x5a: Pokemon_Pinball__U___dispatch_5a(ctx, addr, bank); break;
            case 0x5b: Pokemon_Pinball__U___dispatch_5b(ctx, addr, bank); break;
            case 0x5c: Pokemon_Pinball__U___dispatch_5c(ctx, addr, bank); break;
            case 0x5d: Pokemon_Pinball__U___dispatch_5d(ctx, addr, bank); break;
            case 0x5e: Pokemon_Pinball__U___dispatch_5e(ctx, addr, bank); break;
            case 0x5f: Pokemon_Pinball__U___dispatch_5f(ctx, addr, bank); break;
            case 0x60: Pokemon_Pinball__U___dispatch_60(ctx, addr, bank); break;
            case 0x61: Pokemon_Pinball__U___dispatch_61(ctx, addr, bank); break;
            case 0x62: Pokemon_Pinball__U___dispatch_62(ctx, addr, bank); break;
            case 0x63: Pokemon_Pinball__U___dispatch_63(ctx, addr, bank); break;
            case 0x64: Pokemon_Pinball__U___dispatch_64(ctx, addr, bank); break;
            case 0x65: Pokemon_Pinball__U___dispatch_65(ctx, addr, bank); break;
            case 0x66: Pokemon_Pinball__U___dispatch_66(ctx, addr, bank); break;
            case 0x67: Pokemon_Pinball__U___dispatch_67(ctx, addr, bank); break;
            case 0x68: Pokemon_Pinball__U___dispatch_68(ctx, addr, bank); break;
            case 0x69: Pokemon_Pinball__U___dispatch_69(ctx, addr, bank); break;
            case 0x6a: Pokemon_Pinball__U___dispatch_6a(ctx, addr, bank); break;
            case 0x6b: Pokemon_Pinball__U___dispatch_6b(ctx, addr, bank); break;
            case 0x6c: Pokemon_Pinball__U___dispatch_6c(ctx, addr, bank); break;
            case 0x6d: Pokemon_Pinball__U___dispatch_6d(ctx, addr, bank); break;
            case 0x6e: Pokemon_Pinball__U___dispatch_6e(ctx, addr, bank); break;
            case 0x6f: Pokemon_Pinball__U___dispatch_6f(ctx, addr, bank); break;
            case 0x70: Pokemon_Pinball__U___dispatch_70(ctx, addr, bank); break;
            case 0x71: Pokemon_Pinball__U___dispatch_71(ctx, addr, bank); break;
            case 0x72: Pokemon_Pinball__U___dispatch_72(ctx, addr, bank); break;
            case 0x73: Pokemon_Pinball__U___dispatch_73(ctx, addr, bank); break;
            case 0x74: Pokemon_Pinball__U___dispatch_74(ctx, addr, bank); break;
            case 0x75: Pokemon_Pinball__U___dispatch_75(ctx, addr, bank); break;
            case 0x76: Pokemon_Pinball__U___dispatch_76(ctx, addr, bank); break;
            case 0x77: Pokemon_Pinball__U___dispatch_77(ctx, addr, bank); break;
            case 0x78: Pokemon_Pinball__U___dispatch_78(ctx, addr, bank); break;
            case 0x79: Pokemon_Pinball__U___dispatch_79(ctx, addr, bank); break;
            case 0x7a: Pokemon_Pinball__U___dispatch_7a(ctx, addr, bank); break;
            case 0x7b: Pokemon_Pinball__U___dispatch_7b(ctx, addr, bank); break;
            case 0x7c: Pokemon_Pinball__U___dispatch_7c(ctx, addr, bank); break;
            case 0x7d: Pokemon_Pinball__U___dispatch_7d(ctx, addr, bank); break;
            case 0x7e: Pokemon_Pinball__U___dispatch_7e(ctx, addr, bank); break;
            case 0x7f: Pokemon_Pinball__U___dispatch_7f(ctx, addr, bank); break;
            case 0xff: Pokemon_Pinball__U___dispatch_ff(ctx, addr, bank); break;
            default: gbrt_execute_dispatch_fallback(ctx, bank, addr, GB_DISPATCH_FALLBACK_PAGE_NOT_COMPILED, 0); break;
        }
        if (ctx->single_step_mode) break;
    }
}

void gb_dispatch_call(GBContext* ctx, uint16_t addr) {
    gb_dispatch(ctx, addr);
}

/* Extern reference to ROM data */
extern const uint8_t rom_data[];
extern const size_t rom_size;

const GBConfig* Pokemon_Pinball__U___default_config(void) {
    static const GBConfig config = {
        .model = GB_MODEL_CGB,
        .cgb_compatibility_mode = false,
        .cartridge_supports_cgb = true,
        .cartridge_requires_cgb = false,
        .enable_bootrom = false,
        .enable_audio = true,
        .enable_serial = true,
        .speed_percent = 100,
        .native_presentation_enabled = false,
    };
    return &config;
}

void Pokemon_Pinball__U___init(GBContext* ctx) {
    /* Load ROM data into context */
    gb_context_load_rom(ctx, rom_data, rom_size);
    /* Set MBC type from header */
    ctx->mbc_type = rom_data[0x147];
    gb_context_reset(ctx, true);
}

void Pokemon_Pinball__U___run(GBContext* ctx) {
    // Start the trampoline loop - execution will stay here until stopped
    gb_dispatch(ctx, ctx->pc);
}
