/* Generated by gbrecomp from Pokemon Pinball (U)  */
#include "Pokemon_Pinball__U___internal.h"

/* Shared body at 0b:4000 */
static void body_0b_4000(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4000: goto loc_0b_4000;
        case 0x4001: goto loc_0b_4001;
        case 0x4002: goto loc_0b_4002;
        case 0x4003: goto loc_0b_4003;
        case 0x4004: goto loc_0b_4004;
        case 0x4005: goto loc_0b_4005;
        case 0x4006: goto loc_0b_4006;
        case 0x4008: goto pc_4008;
        case 0x4009: goto pc_4009;
        case 0x400a: goto pc_400a;
        default: break;
    }

loc_0b_4000:
    /* JR NZ,0 */
    /* 0b:4000 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x4002, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_0b_4002;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x4002, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_0b_4002; /* fallthrough */
loc_0b_4001:
    /* NOP */
    /* 0b:4001 */     /* NOP */
    ctx->pc = 0x4002;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_4002:
    /* ADD A,(HL) */
    /* 0b:4002 */     gb_tick(ctx, 7);
    gb_add8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x4003;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_4003:
    /* LD L,A */
    /* 0b:4003 */     ctx->l = ctx->a;
    ctx->pc = 0x4004;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_4004:
    /* DEC C */
    /* 0b:4004 */     ctx->c = gb_dec8(ctx, ctx->c);
    ctx->pc = 0x4005;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_4005:
    /* LD B,H */
    /* 0b:4005 */     ctx->b = ctx->h;
    ctx->pc = 0x4006;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_4006:
    /* AND $6f */
    /* 0b:4006 */     gb_and8(ctx, 0x6f);
    ctx->pc = 0x4008;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC E */
pc_4008:
    /* 0b:4008 */     ctx->e = gb_dec8(ctx, ctx->e);
    ctx->pc = 0x4009;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),L */
pc_4009:
    /* 0b:4009 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->l);
    gb_tick(ctx, 1);
    ctx->pc = 0x400a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RETI */
pc_400a:
    /* 0b:400a */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* fallthrough to function */
    func_0b_400b(ctx);
    return;
}

void func_0b_4000(GBContext* ctx) {
    body_0b_4000(ctx);
}

void func_0b_4001(GBContext* ctx) {
    body_0b_4000(ctx);
}

void func_0b_4003(GBContext* ctx) {
    body_0b_4000(ctx);
}

void func_0b_4004(GBContext* ctx) {
    body_0b_4000(ctx);
}

void func_0b_4005(GBContext* ctx) {
    body_0b_4000(ctx);
}

void func_0b_4006(GBContext* ctx) {
    body_0b_4000(ctx);
}

/* Shared body at 0b:4007 */
static void body_0b_4007(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4007: goto loc_0b_4007;
        case 0x4008: goto pc_4008;
        case 0x4009: goto pc_4009;
        case 0x400a: goto pc_400a;
        default: break;
    }

loc_0b_4007:
    /* LD L,A */
    /* 0b:4007 */     ctx->l = ctx->a;
    ctx->pc = 0x4008;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC E */
pc_4008:
    /* 0b:4008 */     ctx->e = gb_dec8(ctx, ctx->e);
    ctx->pc = 0x4009;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),L */
pc_4009:
    /* 0b:4009 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->l);
    gb_tick(ctx, 1);
    ctx->pc = 0x400a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RETI */
pc_400a:
    /* 0b:400a */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* fallthrough to function */
    func_0b_400b(ctx);
    return;
}

void func_0b_4007(GBContext* ctx) {
    body_0b_4007(ctx);
}

/* Shared body at 0b:400b */
static void body_0b_400b(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x400b: goto loc_0b_400b;
        case 0x400c: goto pc_400c;
        case 0x400d: goto pc_400d;
        case 0x400e: goto loc_0b_400e;
        case 0x400f: goto pc_400f;
        case 0x4010: goto loc_0b_4010;
        case 0x4013: goto loc_0b_4013;
        case 0x4014: goto loc_0b_4014;
        case 0x4015: goto loc_0b_4015;
        case 0x4016: goto pc_4016;
        default: break;
    }

loc_0b_400b:
    /* LD (HL),L */
    /* 0b:400b */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->l);
    gb_tick(ctx, 1);
    ctx->pc = 0x400c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SUB (HL) */
pc_400c:
    /* 0b:400c */     gb_tick(ctx, 7);
    gb_sub8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x400d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* HALT */
pc_400d:
    /* 0b:400d */     gbrt_execute_halt(ctx, 0x400e, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
loc_0b_400e:
    /* LD A,E */
    /* 0b:400e */     ctx->a = ctx->e;
    ctx->pc = 0x400f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),L */
pc_400f:
    /* 0b:400f */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->l);
    gb_tick(ctx, 1);
    ctx->pc = 0x4010;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_4010:
    /* LD SP,$1876 */
    /* 0b:4010 */     ctx->sp = 0x1876;
    ctx->pc = 0x4013;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_4013:
    /* LD C,E */
    /* 0b:4013 */     ctx->c = ctx->e;
    ctx->pc = 0x4014;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_4014:
    /* LD A,B */
    /* 0b:4014 */     ctx->a = ctx->b;
    ctx->pc = 0x4015;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_4015:
    /* LD H,(HL) */
    /* 0b:4015 */     gb_tick(ctx, 7);
    ctx->h = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4016;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RETI */
pc_4016:
    /* 0b:4016 */     gbrt_timed_reti(ctx);
    return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4017 in bank 11 */
    return;
}

void func_0b_400b(GBContext* ctx) {
    body_0b_400b(ctx);
}

void func_0b_400e(GBContext* ctx) {
    body_0b_400b(ctx);
}

void func_0b_4010(GBContext* ctx) {
    body_0b_400b(ctx);
}

void func_0b_4013(GBContext* ctx) {
    body_0b_400b(ctx);
}

void func_0b_4014(GBContext* ctx) {
    body_0b_400b(ctx);
}

void func_0b_4015(GBContext* ctx) {
    body_0b_400b(ctx);
}

/* Shared body at 0b:4011 */
static void body_0b_4011(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4011: goto loc_0b_4011;
        case 0x4012: goto pc_4012;
        case 0x405e: goto loc_0b_405e;
        case 0x405f: goto loc_0b_405f;
        case 0x4060: goto pc_4060;
        case 0x4061: goto loc_0b_4061;
        case 0x4062: goto pc_4062;
        case 0x4063: goto pc_4063;
        case 0x4064: goto pc_4064;
        case 0x4065: goto pc_4065;
        case 0x4066: goto loc_0b_4066;
        case 0x4067: goto loc_0b_4067;
        case 0x4068: goto pc_4068;
        case 0x406b: goto pc_406b;
        case 0x406c: goto pc_406c;
        case 0x406d: goto loc_0b_406d;
        case 0x406e: goto loc_0b_406e;
        case 0x406f: goto loc_0b_406f;
        case 0x4070: goto pc_4070;
        case 0x4071: goto pc_4071;
        case 0x4072: goto pc_4072;
        case 0x4074: goto pc_4074;
        case 0x4075: goto pc_4075;
        case 0x4076: goto pc_4076;
        case 0x4077: goto pc_4077;
        default: break;
    }

loc_0b_4011:
    /* HALT */
    /* 0b:4011 */     gbrt_execute_halt(ctx, 0x4012, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    return;
    if (ctx->single_step_mode) return;
    /* JR 75 */
pc_4012:
    /* 0b:4012 */     gbrt_timed_jump(ctx, 0x405f, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_0b_405f;
    if (ctx->single_step_mode) return;
loc_0b_405e:
    /* LD B,$51 */
    /* 0b:405e */     ctx->b = 0x51;
    ctx->pc = 0x4060;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET NC */
pc_4060:
    /* 0b:4060 */     if (!ctx->f_c) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NC */
    gbrt_timed_jump(ctx, 0x4061, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_0b_4061; /* fallthrough */
loc_0b_405f:
    /* LD D,C */
    /* 0b:405f */     ctx->d = ctx->c;
    ctx->pc = 0x4060;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET NC */
    /* 0b:4060 */     if (!ctx->f_c) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NC */
    gbrt_timed_jump(ctx, 0x4061, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_4061:
    /* LD D,L */
    /* 0b:4061 */     ctx->d = ctx->l;
    ctx->pc = 0x4062;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP E */
pc_4062:
    /* 0b:4062 */     gb_cp8(ctx, ctx->e);
    ctx->pc = 0x4063;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,L */
pc_4063:
    /* 0b:4063 */     ctx->h = ctx->l;
    ctx->pc = 0x4064;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP E */
pc_4064:
    /* 0b:4064 */     gb_cp8(ctx, ctx->e);
    ctx->pc = 0x4065;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,H */
pc_4065:
    /* 0b:4065 */     ctx->d = ctx->h;
    ctx->pc = 0x4066;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_4066:
    /* LD E,A */
    /* 0b:4066 */     ctx->e = ctx->a;
    ctx->pc = 0x4067;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_4067:
    /* LD H,L */
    /* 0b:4067 */     ctx->h = ctx->l;
    ctx->pc = 0x4068;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD SP,$8059 */
pc_4068:
    /* 0b:4068 */     ctx->sp = GB_VRAM_BASE + 0x59;
    ctx->pc = 0x406b;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,H */
pc_406b:
    /* 0b:406b */     ctx->l = ctx->h;
    ctx->pc = 0x406c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,L */
pc_406c:
    /* 0b:406c */     ctx->l = ctx->l;
    ctx->pc = 0x406d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_406d:
    /* LD D,C */
    /* 0b:406d */     ctx->d = ctx->c;
    ctx->pc = 0x406e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_406e:
    /* RST $30 */
    /* 0b:406e */     gbrt_timed_rst(ctx, 0x30, 0x406f);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_30(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_0b_406f:
    /* LD H,A */
    /* 0b:406f */     ctx->h = ctx->a;
    ctx->pc = 0x4070;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC B */
pc_4070:
    /* 0b:4070 */     ctx->b = gb_dec8(ctx, ctx->b);
    ctx->pc = 0x4071;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,H */
pc_4071:
    /* 0b:4071 */     ctx->d = ctx->h;
    ctx->pc = 0x4072;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $64 */
pc_4072:
    /* 0b:4072 */     gb_cp8(ctx, 0x64);
    ctx->pc = 0x4074;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD HL,SP */
pc_4074:
    /* 0b:4074 */     gb_add16(ctx, ctx->sp);
    ctx->pc = 0x4075;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,H */
pc_4075:
    /* 0b:4075 */     ctx->c = ctx->h;
    ctx->pc = 0x4076;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC H */
pc_4076:
    /* 0b:4076 */     ctx->h = gb_inc8(ctx, ctx->h);
    ctx->pc = 0x4077;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,B */
pc_4077:
    /* 0b:4077 */     ctx->c = ctx->b;
    ctx->pc = 0x4078;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4078 in bank 11 */
    return;
}

void func_0b_4011(GBContext* ctx) {
    body_0b_4011(ctx);
}

void func_0b_405e(GBContext* ctx) {
    body_0b_4011(ctx);
}

void func_0b_405f(GBContext* ctx) {
    body_0b_4011(ctx);
}

void func_0b_4066(GBContext* ctx) {
    body_0b_4011(ctx);
}

void func_0b_4067(GBContext* ctx) {
    body_0b_4011(ctx);
}

void func_0b_406d(GBContext* ctx) {
    body_0b_4011(ctx);
}

void func_0b_406e(GBContext* ctx) {
    body_0b_4011(ctx);
}

/* Shared body at 0b:4020 */
static void body_0b_4020(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4020: goto loc_0b_4020;
        case 0x4021: goto loc_0b_4021;
        case 0x4022: goto pc_4022;
        case 0x4023: goto pc_4023;
        case 0x4024: goto pc_4024;
        case 0x4025: goto loc_0b_4025;
        case 0x4026: goto pc_4026;
        case 0x4027: goto pc_4027;
        case 0x4028: goto pc_4028;
        case 0x4029: goto pc_4029;
        case 0x402a: goto pc_402a;
        case 0x402b: goto pc_402b;
        case 0x402c: goto pc_402c;
        case 0x402f: goto pc_402f;
        case 0x4030: goto pc_4030;
        case 0x4031: goto pc_4031;
        case 0x4032: goto pc_4032;
        case 0x4033: goto pc_4033;
        case 0x4034: goto pc_4034;
        case 0x4035: goto pc_4035;
        case 0x4036: goto pc_4036;
        case 0x4037: goto pc_4037;
        case 0x4038: goto pc_4038;
        case 0x4039: goto pc_4039;
        case 0x403a: goto pc_403a;
        case 0x403b: goto pc_403b;
        case 0x403c: goto pc_403c;
        case 0x403d: goto pc_403d;
        case 0x403e: goto pc_403e;
        case 0x403f: goto pc_403f;
        default: break;
    }

loc_0b_4020:
    /* LD D,A */
    /* 0b:4020 */     ctx->d = ctx->a;
    ctx->pc = 0x4021;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_4021:
    /* LD C,L */
    /* 0b:4021 */     ctx->c = ctx->l;
    ctx->pc = 0x4022;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,H */
pc_4022:
    /* 0b:4022 */     ctx->e = ctx->h;
    ctx->pc = 0x4023;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD L,(HL) */
pc_4023:
    /* 0b:4023 */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4024;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET NZ */
pc_4024:
    /* 0b:4024 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x4025, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_0b_4025:
    /* LD L,(HL) */
    /* 0b:4025 */     gb_tick(ctx, 7);
    ctx->l = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4026;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC H */
pc_4026:
    /* 0b:4026 */     ctx->h = gb_inc8(ctx, ctx->h);
    ctx->pc = 0x4027;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_4027:
    /* 0b:4027 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x4028;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,A */
pc_4028:
    /* 0b:4028 */     ctx->a = ctx->a;
    ctx->pc = 0x4029;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),D */
pc_4029:
    /* 0b:4029 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x402a;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,L */
pc_402a:
    /* 0b:402a */     gb_sbc8(ctx, ctx->l);
    ctx->pc = 0x402b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,D */
pc_402b:
    /* 0b:402b */     ctx->b = ctx->d;
    ctx->pc = 0x402c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,($0c4c) */
pc_402c:
    /* 0b:402c */     gb_tick(ctx, 15);
    ctx->a = gb_read8(ctx, 0x0c4c);
    gb_tick(ctx, 1);
    ctx->pc = 0x402f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD H,D */
pc_402f:
    /* 0b:402f */     ctx->h = ctx->d;
    ctx->pc = 0x4030;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR L */
pc_4030:
    /* 0b:4030 */     gb_xor8(ctx, ctx->l);
    ctx->pc = 0x4031;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,B */
pc_4031:
    /* 0b:4031 */     ctx->d = ctx->b;
    ctx->pc = 0x4032;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR E */
pc_4032:
    /* 0b:4032 */     gb_xor8(ctx, ctx->e);
    ctx->pc = 0x4033;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,D */
pc_4033:
    /* 0b:4033 */     ctx->e = ctx->d;
    ctx->pc = 0x4034;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* DEC BC */
pc_4034:
    /* 0b:4034 */     gbrt_timed_dec16(ctx, &ctx->bc);
    ctx->pc = 0x4035;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,E */
pc_4035:
    /* 0b:4035 */     ctx->e = ctx->e;
    ctx->pc = 0x4036;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SBC A,(HL) */
pc_4036:
    /* 0b:4036 */     gb_tick(ctx, 7);
    gb_sbc8(ctx, gb_read8(ctx, ctx->hl));
    gb_tick(ctx, 1);
    ctx->pc = 0x4037;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,L */
pc_4037:
    /* 0b:4037 */     ctx->e = ctx->l;
    ctx->pc = 0x4038;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* EI */
pc_4038:
    /* 0b:4038 */     ctx->ime_pending = 1;
    ctx->pc = 0x4039;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,L */
pc_4039:
    /* 0b:4039 */     ctx->e = ctx->l;
    ctx->pc = 0x403a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,H */
pc_403a:
    /* 0b:403a */     ctx->c = ctx->h;
    ctx->pc = 0x403b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,(HL) */
pc_403b:
    /* 0b:403b */     gb_tick(ctx, 7);
    ctx->b = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x403c;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* INC A */
pc_403c:
    /* 0b:403c */     ctx->a = gb_inc8(ctx, ctx->a);
    ctx->pc = 0x403d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD (HL),E */
pc_403d:
    /* 0b:403d */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->e);
    gb_tick(ctx, 1);
    ctx->pc = 0x403e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* XOR H */
pc_403e:
    /* 0b:403e */     gb_xor8(ctx, ctx->h);
    ctx->pc = 0x403f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,(HL) */
pc_403f:
    /* 0b:403f */     gb_tick(ctx, 7);
    ctx->b = gb_read8(ctx, ctx->hl);
    gb_tick(ctx, 1);
    ctx->pc = 0x4040;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x4040 in bank 11 */
    return;
}

void func_0b_4020(GBContext* ctx) {
    body_0b_4020(ctx);
}

void func_0b_4021(GBContext* ctx) {
    body_0b_4020(ctx);
}

/* Shared body at 0b:4043 */
static void body_0b_4043(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x4043: goto loc_0b_4043;
        case 0x4044: goto pc_4044;
        case 0x4045: goto pc_4045;
        case 0x4046: goto pc_4046;
        case 0x4047: goto pc_4047;
        case 0x4048: goto pc_4048;
        default: break;
    }

loc_0b_4043:
    /* LD (HL),D */
    /* 0b:4043 */     gb_tick(ctx, 7);
    gb_write8(ctx, ctx->hl, ctx->d);
    gb_tick(ctx, 1);
    ctx->pc = 0x4044;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,L */
pc_4044:
    /* 0b:4044 */     ctx->d = ctx->l;
    ctx->pc = 0x4045;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,E */
pc_4045:
    /* 0b:4045 */     ctx->b = ctx->e;
    ctx->pc = 0x4046;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,D */
pc_4046:
    /* 0b:4046 */     ctx->b = ctx->d;
    ctx->pc = 0x4047;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,D */
pc_4047:
    /* 0b:4047 */     ctx->b = ctx->d;
    ctx->pc = 0x4048;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_4048:
    /* 0b:4048 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_0b_4043(GBContext* ctx) {
    body_0b_4043(ctx);
}

