/* Generated by gbrecomp from Pokemon Pinball (U)  */
#include "Pokemon_Pinball__U___internal.h"

/* Shared body at 14:5e09 */
static void body_14_5e09(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x5e09: goto loc_14_5e09;
        case 0x5e0a: goto loc_14_5e0a;
        case 0x5e0b: goto loc_14_5e0b;
        case 0x5e0c: goto pc_5e0c;
        default: break;
    }

loc_14_5e09:
    /* RST $38 */
    /* 14:5e09 */     gbrt_timed_rst(ctx, 0x38, 0x5e0a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5e0a:
    /* RET NZ */
    /* 14:5e0a */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5e0b, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5e0b:
    /* NOP */
    /* 14:5e0b */     /* NOP */
    ctx->pc = 0x5e0c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_5e0c:
    /* 14:5e0c */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x5e0d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x5e0d in bank 20 */
    return;
}

void func_14_5e09(GBContext* ctx) {
    body_14_5e09(ctx);
}

/* Shared body at 14:5e24 */
static void body_14_5e24(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x5e24: goto loc_14_5e24;
        case 0x5e25: goto pc_5e25;
        case 0x5e26: goto loc_14_5e26;
        case 0x5e27: goto loc_14_5e27;
        case 0x5e28: goto loc_14_5e28;
        case 0x5e29: goto pc_5e29;
        case 0x5e2a: goto loc_14_5e2a;
        case 0x5e2b: goto pc_5e2b;
        case 0x5e2c: goto pc_5e2c;
        case 0x5e2e: goto pc_5e2e;
        case 0x5e2f: goto pc_5e2f;
        case 0x5e30: goto loc_14_5e30;
        case 0x5e31: goto pc_5e31;
        default: break;
    }

loc_14_5e24:
    /* NOP */
    /* 14:5e24 */     /* NOP */
    ctx->pc = 0x5e25;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5e25:
    /* 14:5e25 */     /* NOP */
    ctx->pc = 0x5e26;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5e26:
    /* RST $38 */
    /* 14:5e26 */     gbrt_timed_rst(ctx, 0x38, 0x5e27);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5e27:
    /* LDH A,($FF00+$0f) */
    /* 14:5e27 */     gb_tick(ctx, 11);
    ctx->a = gb_read8(ctx, GB_IO_IF);
    gb_tick(ctx, 1);
    ctx->pc = 0x5e29;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5e29:
    /* 14:5e29 */     gbrt_timed_rst(ctx, 0x38, 0x5e2a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_14_5e2a; /* fallthrough */
loc_14_5e28:
    /* RRCA */
    /* 14:5e28 */     gb_rrca(ctx);
    ctx->pc = 0x5e29;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
    /* 14:5e29 */     gbrt_timed_rst(ctx, 0x38, 0x5e2a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5e2a:
    /* ADD A,B */
    /* 14:5e2a */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x5e2b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,A */
pc_5e2b:
    /* 14:5e2b */     ctx->a = ctx->a;
    ctx->pc = 0x5e2c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH ($FF00+$00),A */
pc_5e2c:
    /* 14:5e2c */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_JOYP, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5e2e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RLCA */
pc_5e2e:
    /* 14:5e2e */     gb_rlca(ctx);
    ctx->pc = 0x5e2f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5e2f:
    /* 14:5e2f */     gbrt_timed_rst(ctx, 0x38, 0x5e30);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5e30:
    /* ADD A,B */
    /* 14:5e30 */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x5e31;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,A */
pc_5e31:
    /* 14:5e31 */     ctx->a = ctx->a;
    ctx->pc = 0x5e32;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x5e32 in bank 20 */
    return;
}

void func_14_5e24(GBContext* ctx) {
    body_14_5e24(ctx);
}

void func_14_5e26(GBContext* ctx) {
    body_14_5e24(ctx);
}

void func_14_5e28(GBContext* ctx) {
    body_14_5e24(ctx);
}

/* Shared body at 14:5e69 */
static void body_14_5e69(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x5e69: goto loc_14_5e69;
        case 0x5e6a: goto loc_14_5e6a;
        case 0x5e6b: goto pc_5e6b;
        case 0x5e6c: goto pc_5e6c;
        case 0x5e6f: goto pc_5e6f;
        case 0x5e72: goto pc_5e72;
        case 0x5e73: goto loc_14_5e73;
        case 0x5e74: goto loc_14_5e74;
        case 0x5e75: goto pc_5e75;
        case 0x5e76: goto pc_5e76;
        case 0x5e77: goto loc_14_5e77;
        case 0x5e79: goto pc_5e79;
        case 0x5e7a: goto pc_5e7a;
        case 0x5e7b: goto loc_14_5e7b;
        case 0x5e7c: goto pc_5e7c;
        case 0x5e7e: goto pc_5e7e;
        case 0x5e7f: goto pc_5e7f;
        case 0x5e80: goto pc_5e80;
        case 0x5e82: goto pc_5e82;
        default: break;
    }

loc_14_5e69:
    /* RST $38 */
    /* 14:5e69 */     gbrt_timed_rst(ctx, 0x38, 0x5e6a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5e6a:
    /* ADD A,B */
    /* 14:5e6a */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x5e6b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5e6b:
    /* 14:5e6b */     /* NOP */
    ctx->pc = 0x5e6c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$f0ff */
pc_5e6c:
    /* 14:5e6c */     ctx->bc = 0xf0ff;
    ctx->pc = 0x5e6f;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$80ff */
pc_5e6f:
    /* 14:5e6f */     ctx->bc = GB_VRAM_BASE + 0xff;
    ctx->pc = 0x5e72;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5e72:
    /* 14:5e72 */     gbrt_timed_rst(ctx, 0x38, 0x5e73);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5e73:
    /* RET NZ */
    /* 14:5e73 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5e74, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5e74:
    /* NOP */
    /* 14:5e74 */     /* NOP */
    ctx->pc = 0x5e75;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5e75:
    /* 14:5e75 */     /* NOP */
    ctx->pc = 0x5e76;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5e76:
    /* 14:5e76 */     gbrt_timed_rst(ctx, 0x38, 0x5e77);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5e77:
    /* LD HL,SP+0 */
    /* 14:5e77 */     gbrt_timed_ld_hl_sp_n(ctx, 0x5e78);
    ctx->pc = 0x5e79;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,A */
pc_5e79:
    /* 14:5e79 */     ctx->a = ctx->a;
    ctx->pc = 0x5e7a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET NZ */
pc_5e7a:
    /* 14:5e7a */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5e7b, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5e7b:
    /* RRA */
    /* 14:5e7b */     gb_rra(ctx);
    ctx->pc = 0x5e7c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH ($FF00+$00),A */
pc_5e7c:
    /* 14:5e7c */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_JOYP, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5e7e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5e7e:
    /* 14:5e7e */     /* NOP */
    ctx->pc = 0x5e7f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_5e7f:
    /* 14:5e7f */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x5e80;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CP $00 */
pc_5e80:
    /* 14:5e80 */     gb_cp8(ctx, 0x00);
    ctx->pc = 0x5e82;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_5e82:
    /* 14:5e82 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x5e83;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* warning: fallthrough to unanalyzed code at 0x5e83 in bank 20 */
    return;
}

void func_14_5e69(GBContext* ctx) {
    body_14_5e69(ctx);
}

/* Shared body at 14:5ee0 */
static void body_14_5ee0(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x5ee0: goto loc_14_5ee0;
        case 0x5ee2: goto pc_5ee2;
        case 0x5ee3: goto loc_14_5ee3;
        case 0x5ee5: goto pc_5ee5;
        case 0x5ee6: goto pc_5ee6;
        case 0x5ee7: goto pc_5ee7;
        case 0x5ee8: goto pc_5ee8;
        case 0x5ee9: goto pc_5ee9;
        case 0x5eea: goto loc_14_5eea;
        case 0x5eec: goto pc_5eec;
        case 0x5eed: goto loc_14_5eed;
        default: break;
    }

loc_14_5ee0:
    /* LDH ($FF00+$01),A */
    /* 14:5ee0 */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_SB, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5ee2;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5ee2:
    /* 14:5ee2 */     gbrt_timed_rst(ctx, 0x38, 0x5ee3);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5ee3:
    /* LDH A,($FF00+$7f) */
    /* 14:5ee3 */     gb_tick(ctx, 11);
    ctx->a = gb_read8(ctx, GB_IO_BASE + 0x7f);
    gb_tick(ctx, 1);
    ctx->pc = 0x5ee5;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* ADD A,B */
pc_5ee5:
    /* 14:5ee5 */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x5ee6;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5ee6:
    /* 14:5ee6 */     /* NOP */
    ctx->pc = 0x5ee7;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5ee7:
    /* 14:5ee7 */     /* NOP */
    ctx->pc = 0x5ee8;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RLCA */
pc_5ee8:
    /* 14:5ee8 */     gb_rlca(ctx);
    ctx->pc = 0x5ee9;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5ee9:
    /* 14:5ee9 */     gbrt_timed_rst(ctx, 0x38, 0x5eea);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5eea:
    /* LDH ($FF00+$03),A */
    /* 14:5eea */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_BASE + 0x03, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5eec;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5eec:
    /* 14:5eec */     gbrt_timed_rst(ctx, 0x38, 0x5eed);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5eed:
    goto loc_14_5eed; /* fallthrough */
}

void func_14_5ee0(GBContext* ctx) {
    body_14_5ee0(ctx);
}

/* Shared body at 14:5ef8 */
static void body_14_5ef8(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x5ef8: goto loc_14_5ef8;
        case 0x5ef9: goto loc_14_5ef9;
        case 0x5efa: goto pc_5efa;
        case 0x5efb: goto pc_5efb;
        case 0x5efc: goto pc_5efc;
        case 0x5efd: goto pc_5efd;
        case 0x5efe: goto loc_14_5efe;
        case 0x5eff: goto loc_14_5eff;
        case 0x5f00: goto loc_14_5f00;
        case 0x5f01: goto loc_14_5f01;
        case 0x5f02: goto loc_14_5f02;
        case 0x5f03: goto loc_14_5f03;
        case 0x5f04: goto pc_5f04;
        case 0x5f05: goto loc_14_5f05;
        case 0x5f06: goto pc_5f06;
        case 0x5f07: goto loc_14_5f07;
        case 0x5f08: goto loc_14_5f08;
        case 0x5f09: goto loc_14_5f09;
        case 0x5f0a: goto loc_14_5f0a;
        case 0x5f0b: goto loc_14_5f0b;
        case 0x5f0c: goto loc_14_5f0c;
        case 0x5f0d: goto loc_14_5f0d;
        case 0x5f0e: goto pc_5f0e;
        case 0x5f0f: goto loc_14_5f0f;
        case 0x5f10: goto loc_14_5f10;
        case 0x5f11: goto pc_5f11;
        case 0x5f12: goto loc_14_5f12;
        case 0x5f13: goto loc_14_5f13;
        case 0x5f14: goto pc_5f14;
        case 0x5f15: goto loc_14_5f15;
        case 0x5f16: goto loc_14_5f16;
        case 0x5f18: goto pc_5f18;
        case 0x5f19: goto pc_5f19;
        case 0x5f1a: goto pc_5f1a;
        case 0x5f1b: goto pc_5f1b;
        case 0x5f1c: goto loc_14_5f1c;
        case 0x5f1d: goto loc_14_5f1d;
        case 0x5f1e: goto pc_5f1e;
        case 0x5f1f: goto loc_14_5f1f;
        case 0x5f20: goto loc_14_5f20;
        case 0x5f21: goto loc_14_5f21;
        case 0x5f22: goto pc_5f22;
        case 0x5f23: goto pc_5f23;
        case 0x5f24: goto pc_5f24;
        case 0x5f25: goto pc_5f25;
        case 0x5f26: goto loc_14_5f26;
        case 0x5f27: goto loc_14_5f27;
        case 0x5f28: goto pc_5f28;
        case 0x5f29: goto loc_14_5f29;
        case 0x5f2a: goto loc_14_5f2a;
        case 0x5f2b: goto loc_14_5f2b;
        case 0x5f2c: goto loc_14_5f2c;
        case 0x5f2d: goto pc_5f2d;
        case 0x5f2e: goto pc_5f2e;
        case 0x5f2f: goto pc_5f2f;
        case 0x5f30: goto loc_14_5f30;
        case 0x5f32: goto pc_5f32;
        case 0x5f33: goto loc_14_5f33;
        case 0x5f34: goto loc_14_5f34;
        case 0x5f35: goto loc_14_5f35;
        case 0x5f36: goto loc_14_5f36;
        case 0x5f37: goto pc_5f37;
        case 0x5f38: goto pc_5f38;
        case 0x5f3b: goto pc_5f3b;
        case 0x5f3c: goto pc_5f3c;
        case 0x5f3d: goto loc_14_5f3d;
        case 0x5f3e: goto loc_14_5f3e;
        case 0x5f3f: goto loc_14_5f3f;
        case 0x5f40: goto loc_14_5f40;
        case 0x5f41: goto pc_5f41;
        case 0x5f42: goto pc_5f42;
        case 0x5f43: goto pc_5f43;
        case 0x5f44: goto pc_5f44;
        case 0x5f45: goto loc_14_5f45;
        case 0x5f46: goto pc_5f46;
        case 0x5f47: goto pc_5f47;
        case 0x5f48: goto loc_14_5f48;
        case 0x5f49: goto loc_14_5f49;
        case 0x5f4a: goto loc_14_5f4a;
        case 0x5f4b: goto pc_5f4b;
        case 0x5f4c: goto pc_5f4c;
        case 0x5f4d: goto pc_5f4d;
        case 0x5f4e: goto pc_5f4e;
        case 0x5f4f: goto loc_14_5f4f;
        case 0x5f51: goto pc_5f51;
        case 0x5f52: goto loc_14_5f52;
        case 0x5f53: goto loc_14_5f53;
        case 0x5f55: goto pc_5f55;
        case 0x5f56: goto loc_14_5f56;
        case 0x5f57: goto pc_5f57;
        case 0x5f58: goto pc_5f58;
        case 0x5f59: goto pc_5f59;
        case 0x5f5a: goto loc_14_5f5a;
        case 0x5f5b: goto pc_5f5b;
        case 0x5f5c: goto pc_5f5c;
        case 0x5f5d: goto loc_14_5f5d;
        case 0x5f5e: goto loc_14_5f5e;
        case 0x5f5f: goto pc_5f5f;
        case 0x5f61: goto loc_14_5f61;
        case 0x5f62: goto loc_14_5f62;
        case 0x5f63: goto pc_5f63;
        case 0x5f64: goto loc_14_5f64;
        case 0x5f67: goto loc_14_5f67;
        case 0x5f6a: goto loc_14_5f6a;
        case 0x5f6d: goto loc_14_5f6d;
        case 0x5f70: goto loc_14_5f70;
        case 0x5f73: goto loc_14_5f73;
        case 0x5f76: goto loc_14_5f76;
        case 0x5f79: goto loc_14_5f79;
        case 0x5f7c: goto loc_14_5f7c;
        case 0x5f7f: goto loc_14_5f7f;
        case 0x5f82: goto loc_14_5f82;
        case 0x5f83: goto loc_14_5f83;
        case 0x5f84: goto pc_5f84;
        case 0x5f85: goto loc_14_5f85;
        case 0x5f87: goto loc_14_5f87;
        case 0x5f88: goto loc_14_5f88;
        case 0x5f8b: goto loc_14_5f8b;
        case 0x5f8d: goto loc_14_5f8d;
        case 0x5f8e: goto loc_14_5f8e;
        case 0x5f8f: goto loc_14_5f8f;
        case 0x5f90: goto pc_5f90;
        case 0x5f91: goto loc_14_5f91;
        case 0x5f93: goto loc_14_5f93;
        default: break;
    }

loc_14_5ef8:
    /* RST $38 */
    /* 14:5ef8 */     gbrt_timed_rst(ctx, 0x38, 0x5ef9);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5ef9:
    /* NOP */
    /* 14:5ef9 */     /* NOP */
    ctx->pc = 0x5efa;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5efa:
    /* 14:5efa */     /* NOP */
    ctx->pc = 0x5efb;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5efb:
    /* 14:5efb */     /* NOP */
    ctx->pc = 0x5efc;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_5efc:
    /* 14:5efc */     gb_rrca(ctx);
    ctx->pc = 0x5efd;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5efd:
    /* 14:5efd */     gbrt_timed_rst(ctx, 0x38, 0x5efe);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5efe:
    /* RET NZ */
    /* 14:5efe */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5eff, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5eff:
    /* INC BC */
    /* 14:5eff */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x5f00;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f00:
    /* RST $38 */
    /* 14:5f00 */     gbrt_timed_rst(ctx, 0x38, 0x5f01);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f01:
    /* RST $28 */
    /* 14:5f01 */     gbrt_timed_rst(ctx, 0x28, 0x5f02);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_28(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f02:
    /* RST $38 */
    /* 14:5f02 */     gbrt_timed_rst(ctx, 0x38, 0x5f03);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f03:
    /* NOP */
    /* 14:5f03 */     /* NOP */
    ctx->pc = 0x5f04;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5f04:
    /* 14:5f04 */     /* NOP */
    ctx->pc = 0x5f05;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f05:
    /* NOP */
    /* 14:5f05 */     /* NOP */
    ctx->pc = 0x5f06;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_5f06:
    /* 14:5f06 */     gb_rrca(ctx);
    ctx->pc = 0x5f07;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f07:
    /* RST $38 */
    /* 14:5f07 */     gbrt_timed_rst(ctx, 0x38, 0x5f08);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f08:
    /* RET NZ */
    /* 14:5f08 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5f09, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f09:
    /* RLCA */
    /* 14:5f09 */     gb_rlca(ctx);
    ctx->pc = 0x5f0a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f0a:
    /* RST $38 */
    /* 14:5f0a */     gbrt_timed_rst(ctx, 0x38, 0x5f0b);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f0b:
    /* RST $38 */
    /* 14:5f0b */     gbrt_timed_rst(ctx, 0x38, 0x5f0c);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f0c:
    /* RST $38 */
    /* 14:5f0c */     gbrt_timed_rst(ctx, 0x38, 0x5f0d);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f0d:
    /* NOP */
    /* 14:5f0d */     /* NOP */
    ctx->pc = 0x5f0e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5f0e:
    /* 14:5f0e */     /* NOP */
    ctx->pc = 0x5f0f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f0f:
    /* NOP */
    /* 14:5f0f */     /* NOP */
    ctx->pc = 0x5f10;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f10:
    /* RRCA */
    /* 14:5f10 */     gb_rrca(ctx);
    ctx->pc = 0x5f11;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5f11:
    /* 14:5f11 */     gbrt_timed_rst(ctx, 0x38, 0x5f12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f12:
    /* RET NZ */
    /* 14:5f12 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5f13, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f13:
    /* RLCA */
    /* 14:5f13 */     gb_rlca(ctx);
    ctx->pc = 0x5f14;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5f14:
    /* 14:5f14 */     gbrt_timed_rst(ctx, 0x38, 0x5f15);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f15:
    /* RST $38 */
    /* 14:5f15 */     gbrt_timed_rst(ctx, 0x38, 0x5f16);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f16:
    /* CP $00 */
    /* 14:5f16 */     gb_cp8(ctx, 0x00);
    ctx->pc = 0x5f18;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5f18:
    /* 14:5f18 */     /* NOP */
    ctx->pc = 0x5f19;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5f19:
    /* 14:5f19 */     /* NOP */
    ctx->pc = 0x5f1a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRCA */
pc_5f1a:
    /* 14:5f1a */     gb_rrca(ctx);
    ctx->pc = 0x5f1b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5f1b:
    /* 14:5f1b */     gbrt_timed_rst(ctx, 0x38, 0x5f1c);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f1c:
    /* RET NZ */
    /* 14:5f1c */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5f1d, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f1d:
    /* RLCA */
    /* 14:5f1d */     gb_rlca(ctx);
    ctx->pc = 0x5f1e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5f1e:
    /* 14:5f1e */     gbrt_timed_rst(ctx, 0x38, 0x5f1f);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f1f:
    /* RST $38 */
    /* 14:5f1f */     gbrt_timed_rst(ctx, 0x38, 0x5f20);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f20:
    /* RST $38 */
    /* 14:5f20 */     gbrt_timed_rst(ctx, 0x38, 0x5f21);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f21:
    /* ADD A,B */
    /* 14:5f21 */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x5f22;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5f22:
    /* 14:5f22 */     /* NOP */
    ctx->pc = 0x5f23;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5f23:
    /* 14:5f23 */     /* NOP */
    ctx->pc = 0x5f24;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RLCA */
pc_5f24:
    /* 14:5f24 */     gb_rlca(ctx);
    ctx->pc = 0x5f25;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5f25:
    /* 14:5f25 */     gbrt_timed_rst(ctx, 0x38, 0x5f26);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f26:
    /* LDH ($FF00+$03),A */
    /* 14:5f26 */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_BASE + 0x03, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5f28;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5f28:
    /* 14:5f28 */     gbrt_timed_rst(ctx, 0x38, 0x5f29);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_14_5f29; /* fallthrough */
loc_14_5f27:
    /* INC BC */
    /* 14:5f27 */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x5f28;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
    /* 14:5f28 */     gbrt_timed_rst(ctx, 0x38, 0x5f29);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f29:
    /* RST $38 */
    /* 14:5f29 */     gbrt_timed_rst(ctx, 0x38, 0x5f2a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f2a:
    /* RST $38 */
    /* 14:5f2a */     gbrt_timed_rst(ctx, 0x38, 0x5f2b);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f2b:
    /* RET NZ */
    /* 14:5f2b */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5f2c, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f2c:
    /* NOP */
    /* 14:5f2c */     /* NOP */
    ctx->pc = 0x5f2d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5f2d:
    /* 14:5f2d */     /* NOP */
    ctx->pc = 0x5f2e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RLCA */
pc_5f2e:
    /* 14:5f2e */     gb_rlca(ctx);
    ctx->pc = 0x5f2f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5f2f:
    /* 14:5f2f */     gbrt_timed_rst(ctx, 0x38, 0x5f30);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f30:
    /* LDH ($FF00+$03),A */
    /* 14:5f30 */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_BASE + 0x03, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5f32;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5f32:
    /* 14:5f32 */     gbrt_timed_rst(ctx, 0x38, 0x5f33);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f33:
    /* RST $38 */
    /* 14:5f33 */     gbrt_timed_rst(ctx, 0x38, 0x5f34);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f34:
    /* RST $38 */
    /* 14:5f34 */     gbrt_timed_rst(ctx, 0x38, 0x5f35);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f35:
    /* RET NZ */
    /* 14:5f35 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5f36, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f36:
    /* NOP */
    /* 14:5f36 */     /* NOP */
    ctx->pc = 0x5f37;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5f37:
    /* 14:5f37 */     /* NOP */
    ctx->pc = 0x5f38;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD BC,$f8ff */
pc_5f38:
    /* 14:5f38 */     ctx->bc = 0xf8ff;
    ctx->pc = 0x5f3b;
    gb_tick(ctx, 12);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5f3b:
    /* 14:5f3b */     /* NOP */
    ctx->pc = 0x5f3c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5f3c:
    /* 14:5f3c */     gbrt_timed_rst(ctx, 0x38, 0x5f3d);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f3d:
    /* RST $38 */
    /* 14:5f3d */     gbrt_timed_rst(ctx, 0x38, 0x5f3e);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f3e:
    /* RST $38 */
    /* 14:5f3e */     gbrt_timed_rst(ctx, 0x38, 0x5f3f);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f3f:
    /* RET NZ */
    /* 14:5f3f */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5f40, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f40:
    /* NOP */
    /* 14:5f40 */     /* NOP */
    ctx->pc = 0x5f41;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5f41:
    /* 14:5f41 */     /* NOP */
    ctx->pc = 0x5f42;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5f42:
    /* 14:5f42 */     /* NOP */
    ctx->pc = 0x5f43;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,A */
pc_5f43:
    /* 14:5f43 */     ctx->a = ctx->a;
    ctx->pc = 0x5f44;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5f44:
    /* 14:5f44 */     gbrt_timed_rst(ctx, 0x38, 0x5f45);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f45:
    /* NOP */
    /* 14:5f45 */     /* NOP */
    ctx->pc = 0x5f46;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* CCF */
pc_5f46:
    /* 14:5f46 */     ctx->f_n = 0; ctx->f_h = 0; ctx->f_c = !ctx->f_c;
    ctx->pc = 0x5f47;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5f47:
    /* 14:5f47 */     gbrt_timed_rst(ctx, 0x38, 0x5f48);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f48:
    /* RST $38 */
    /* 14:5f48 */     gbrt_timed_rst(ctx, 0x38, 0x5f49);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f49:
    /* RET NZ */
    /* 14:5f49 */     if (!ctx->f_z) {
        gbrt_timed_ret_cc(ctx);
        return;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5f4a, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f4a:
    /* NOP */
    /* 14:5f4a */     /* NOP */
    ctx->pc = 0x5f4b;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5f4b:
    /* 14:5f4b */     /* NOP */
    ctx->pc = 0x5f4c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5f4c:
    /* 14:5f4c */     /* NOP */
    ctx->pc = 0x5f4d;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RRA */
pc_5f4d:
    /* 14:5f4d */     gb_rra(ctx);
    ctx->pc = 0x5f4e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5f4e:
    /* 14:5f4e */     gbrt_timed_rst(ctx, 0x38, 0x5f4f);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f4f:
    /* LDH ($FF00+$0f),A */
    /* 14:5f4f */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_IF, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5f51;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RST $38 */
pc_5f51:
    /* 14:5f51 */     gbrt_timed_rst(ctx, 0x38, 0x5f52);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f52:
    /* RST $38 */
    /* 14:5f52 */     gbrt_timed_rst(ctx, 0x38, 0x5f53);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    rst_38(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f53:
    /* LDH A,($FF00+$00) */
    /* 14:5f53 */     gb_tick(ctx, 11);
    ctx->a = gb_read8(ctx, GB_IO_JOYP);
    gb_tick(ctx, 1);
    ctx->pc = 0x5f55;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* NOP */
pc_5f55:
    /* 14:5f55 */     /* NOP */
    ctx->pc = 0x5f56;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f56:
    /* LD A,(HL+) */
    /* 14:5f56 */     ctx->a = gbrt_timed_hl_read_auto(ctx, 1);
    ctx->pc = 0x5f57;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD C,A */
pc_5f57:
    /* 14:5f57 */     ctx->c = ctx->a;
    ctx->pc = 0x5f58;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,(HL+) */
pc_5f58:
    /* 14:5f58 */     ctx->a = gbrt_timed_hl_read_auto(ctx, 1);
    ctx->pc = 0x5f59;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD B,A */
pc_5f59:
    /* 14:5f59 */     ctx->b = ctx->a;
    ctx->pc = 0x5f5a;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f5a:
    /* LD A,(HL+) */
    /* 14:5f5a */     ctx->a = gbrt_timed_hl_read_auto(ctx, 1);
    ctx->pc = 0x5f5b;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD D,A */
pc_5f5b:
    /* 14:5f5b */     ctx->d = ctx->a;
    ctx->pc = 0x5f5c;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD A,$03 */
pc_5f5c:
    /* 14:5f5c */     ctx->a = 0x03;
    ctx->pc = 0x5f5e;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    goto loc_14_5f5e; /* fallthrough */
loc_14_5f5d:
    /* INC BC */
    /* 14:5f5d */     gbrt_timed_inc16(ctx, &ctx->bc);
    ctx->pc = 0x5f5e;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f5e:
    /* DEC A */
    /* 14:5f5e */     ctx->a = gb_dec8(ctx, ctx->a);
    ctx->pc = 0x5f5f;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-3 */
pc_5f5f:
    /* 14:5f5f */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x5f5e, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_14_5f5e;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5f61, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f61:
    /* CALL $5f94 */
    /* 14:5f61 */     gbrt_timed_call(ctx, 0x5f94, 0x5f64);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5f94(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_14_5f64; /* fallthrough */
loc_14_5f62:
    /* SUB H */
    /* 14:5f62 */     gb_sub8(ctx, ctx->h);
    ctx->pc = 0x5f63;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,A */
pc_5f63:
    /* 14:5f63 */     ctx->e = ctx->a;
    ctx->pc = 0x5f64;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f64:
    /* CALL $5fa0 */
    /* 14:5f64 */     gbrt_timed_call(ctx, 0x5fa0, 0x5f67);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5fa0(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f67:
    /* CALL $5f94 */
    /* 14:5f67 */     gbrt_timed_call(ctx, 0x5f94, 0x5f6a);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5f94(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f6a:
    /* CALL $5fa0 */
    /* 14:5f6a */     gbrt_timed_call(ctx, 0x5fa0, 0x5f6d);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5fa0(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f6d:
    /* CALL $5f94 */
    /* 14:5f6d */     gbrt_timed_call(ctx, 0x5f94, 0x5f70);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5f94(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f70:
    /* CALL $5fa0 */
    /* 14:5f70 */     gbrt_timed_call(ctx, 0x5fa0, 0x5f73);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5fa0(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f73:
    /* CALL $5f94 */
    /* 14:5f73 */     gbrt_timed_call(ctx, 0x5f94, 0x5f76);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5f94(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f76:
    /* CALL $5fa0 */
    /* 14:5f76 */     gbrt_timed_call(ctx, 0x5fa0, 0x5f79);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5fa0(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f79:
    /* CALL $5f94 */
    /* 14:5f79 */     gbrt_timed_call(ctx, 0x5f94, 0x5f7c);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5f94(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f7c:
    /* CALL $5fa0 */
    /* 14:5f7c */     gbrt_timed_call(ctx, 0x5fa0, 0x5f7f);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5fa0(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f7f:
    /* CALL $5f94 */
    /* 14:5f7f */     gbrt_timed_call(ctx, 0x5f94, 0x5f82);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5f94(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f82:
    /* CALL $5fa0 */
    /* 14:5f82 */     gbrt_timed_call(ctx, 0x5fa0, 0x5f85);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5fa0(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_14_5f85; /* fallthrough */
loc_14_5f83:
    /* AND B */
    /* 14:5f83 */     gb_and8(ctx, ctx->b);
    ctx->pc = 0x5f84;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LD E,A */
pc_5f84:
    /* 14:5f84 */     ctx->e = ctx->a;
    ctx->pc = 0x5f85;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f85:
    /* CALL $5f94 */
    /* 14:5f85 */     gbrt_timed_call(ctx, 0x5f94, 0x5f88);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5f94(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_14_5f88; /* fallthrough */
loc_14_5f87:
    /* LD E,A */
    /* 14:5f87 */     ctx->e = ctx->a;
    ctx->pc = 0x5f88;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f88:
    /* CALL $5fa0 */
    /* 14:5f88 */     gbrt_timed_call(ctx, 0x5fa0, 0x5f8b);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5fa0(ctx);
    return;
    if (ctx->single_step_mode) return;
loc_14_5f8b:
    /* CALL $5f94 */
    /* 14:5f8b */     gbrt_timed_call(ctx, 0x5f94, 0x5f8e);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    func_14_5f94(ctx);
    return;
    if (ctx->single_step_mode) return;
    goto loc_14_5f8e; /* fallthrough */
loc_14_5f8d:
    /* LD E,A */
    /* 14:5f8d */     ctx->e = ctx->a;
    ctx->pc = 0x5f8e;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f8e:
    /* DEC BC */
    /* 14:5f8e */     gbrt_timed_dec16(ctx, &ctx->bc);
    ctx->pc = 0x5f8f;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f8f:
    /* LD A,C */
    /* 14:5f8f */     ctx->a = ctx->c;
    ctx->pc = 0x5f90;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* OR B */
pc_5f90:
    /* 14:5f90 */     gb_or8(ctx, ctx->b);
    ctx->pc = 0x5f91;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f91:
    /* JR NZ,-57 */
    /* 14:5f91 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x5f5a, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_14_5f5a;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5f93, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5f93:
    /* RET */
    /* 14:5f93 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_14_5ef8(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f00(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f01(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f02(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f05(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f07(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f08(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f0a(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f0f(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f10(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f26(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f27(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f2a(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f56(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f5d(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f62(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f82(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f83(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f87(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f8b(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f8d(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f8f(GBContext* ctx) {
    body_14_5ef8(ctx);
}

void func_14_5f91(GBContext* ctx) {
    body_14_5ef8(ctx);
}

/* Shared body at 14:5f94 */
static void body_14_5f94(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x5f94: goto loc_14_5f94;
        case 0x5f95: goto pc_5f95;
        case 0x5f97: goto pc_5f97;
        case 0x5f99: goto pc_5f99;
        case 0x5f9b: goto pc_5f9b;
        case 0x5f9d: goto pc_5f9d;
        case 0x5f9f: goto pc_5f9f;
        default: break;
    }

loc_14_5f94:
    /* LD A,D */
    /* 14:5f94 */     ctx->a = ctx->d;
    ctx->pc = 0x5f95;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* AND $80 */
pc_5f95:
    /* 14:5f95 */     gb_and8(ctx, 0x80);
    ctx->pc = 0x5f97;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SRL r */
pc_5f97:
    /* 14:5f97 */     ctx->a = gb_srl(ctx, ctx->a);
    ctx->pc = 0x5f99;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SRL r */
pc_5f99:
    /* 14:5f99 */     ctx->a = gb_srl(ctx, ctx->a);
    ctx->pc = 0x5f9b;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH ($FF00+$1c),A */
pc_5f9b:
    /* 14:5f9b */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_NR32, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5f9d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SLA r */
pc_5f9d:
    /* 14:5f9d */     ctx->d = gb_sla(ctx, ctx->d);
    ctx->pc = 0x5f9f;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_5f9f:
    /* 14:5f9f */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_14_5f94(GBContext* ctx) {
    body_14_5f94(ctx);
}

/* Shared body at 14:5f96 */
static void body_14_5f96(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x5f96: goto loc_14_5f96;
        case 0x5f97: goto pc_5f97;
        case 0x5f99: goto pc_5f99;
        case 0x5f9b: goto pc_5f9b;
        case 0x5f9d: goto pc_5f9d;
        case 0x5f9f: goto pc_5f9f;
        default: break;
    }

loc_14_5f96:
    /* ADD A,B */
    /* 14:5f96 */     gb_add8(ctx, ctx->b);
    ctx->pc = 0x5f97;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SRL r */
pc_5f97:
    /* 14:5f97 */     ctx->a = gb_srl(ctx, ctx->a);
    ctx->pc = 0x5f99;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SRL r */
pc_5f99:
    /* 14:5f99 */     ctx->a = gb_srl(ctx, ctx->a);
    ctx->pc = 0x5f9b;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* LDH ($FF00+$1c),A */
pc_5f9b:
    /* 14:5f9b */     gb_tick(ctx, 11);
    gb_write8(ctx, GB_IO_NR32, ctx->a);
    gb_tick(ctx, 1);
    ctx->pc = 0x5f9d;
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* SLA r */
pc_5f9d:
    /* 14:5f9d */     ctx->d = gb_sla(ctx, ctx->d);
    ctx->pc = 0x5f9f;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* RET */
pc_5f9f:
    /* 14:5f9f */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_14_5f96(GBContext* ctx) {
    body_14_5f96(ctx);
}

/* Shared body at 14:5fa0 */
static void body_14_5fa0(GBContext* ctx) {
    gbrt_note_generated_direct_transition(ctx);
    switch (ctx->pc) {
        case 0x5fa0: goto loc_14_5fa0;
        case 0x5fa2: goto loc_14_5fa2;
        case 0x5fa3: goto pc_5fa3;
        case 0x5fa5: goto loc_14_5fa5;
        default: break;
    }

loc_14_5fa0:
    /* LD A,$03 */
    /* 14:5fa0 */     ctx->a = 0x03;
    ctx->pc = 0x5fa2;
    gb_tick(ctx, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5fa2:
    /* DEC A */
    /* 14:5fa2 */     ctx->a = gb_dec8(ctx, ctx->a);
    ctx->pc = 0x5fa3;
    gb_tick(ctx, 4);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
    /* JR NZ,-3 */
pc_5fa3:
    /* 14:5fa3 */     if (!ctx->f_z) {
        gbrt_timed_jump(ctx, 0x5fa2, 12);
        if (gbrt_generated_safepoint(ctx)) return;
        if (ctx->single_step_mode) return;
        goto loc_14_5fa2;
    } /* NZ */
    gbrt_timed_jump(ctx, 0x5fa5, 8);
    if (gbrt_generated_safepoint(ctx)) return;
    if (ctx->single_step_mode) return;
loc_14_5fa5:
    /* RET */
    /* 14:5fa5 */     gbrt_timed_ret(ctx);
    return;
    if (ctx->single_step_mode) return;
}

void func_14_5fa0(GBContext* ctx) {
    body_14_5fa0(ctx);
}

