/* Generated by gbrecomp */
#ifndef Pokemon_Pinball__U___H
#define Pokemon_Pinball__U___H

#include "gbrt.h"

const GBConfig* Pokemon_Pinball__U___default_config(void);
void Pokemon_Pinball__U___run(GBContext* ctx);
void Pokemon_Pinball__U___init(GBContext* ctx);
int Pokemon_Pinball__U___main(int argc, char* argv[]);

#endif
